"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import styles from "./admin.module.css";

type Module="settings"|"hero"|"news"|"pages"|"comments"|"media"|"analytics"|"audit"|"search"|"email"|"backup";
type CmsEntry={id:string;kind:string;slug:string;title:string;subtitle:string|null;excerpt:string|null;body:string|null;status:string;featured:boolean;pinned:boolean;sortOrder:number;publishAt:string|null;imageUrl:string|null;videoUrl:string|null;buttonText:string|null;buttonUrl:string|null;updatedAt:string};
type CommentItem={id:string;body:string;status:string;targetType:string;targetId:string;pinned:boolean;likeCount:number;reportCount:number;createdAt:string};
type MediaItem={id:string;name:string;folder:string;kind:string;mimeType:string;url:string;sizeBytes:string;altText:string|null;createdAt:string};
type AuditItem={id:string;actor:string;role:string;action:string;entity:string|null;summary:string;ipAddress:string|null;createdAt:string};
type SearchRule={id:string;keyword:string;type:string;weight:number;active:boolean};
type EmailTemplate={id:string;key:string;name:string;subject:string;html:string;text:string|null;active:boolean};
type WebsiteSettings={
  general:{websiteName:string;logo:string;favicon:string;footerLogo:string;websiteDescription:string;seoDescription:string;keywords:string[];contactEmail:string;supportEmail:string;phone:string;officeAddress:string;socialLinks:Record<string,string>;socialMedia:Array<{platform:"facebook"|"tiktok"|"youtube"|"audiomack";enabled:boolean;url:string;order:number;customIcon:string}>};
  appearance:{primaryColor:string;secondaryColor:string;accentColor:string;defaultTheme:"light"|"dark"|"system";typography:string;heroAnimationSpeed:number};
  homepage:{enabledSections:Record<string,boolean>;sectionOrder:string[];featuredSections:string[];banner:string};
  system:Record<string,boolean>;
  utilityDock:{position:"right"|"left";visibility:"entire"|"homepage";liveStatus:"online"|"offline";reportUrl:string;searchEnabled:boolean;shareEnabled:boolean};
  commentPolicy:{approvalRequired:boolean;requireApprovalForNewUsers:boolean;minimumApprovedForTrust:number;spamDetection:boolean;maximumLinks:number;maximumCharacters:number;allowReplies:boolean;allowEmojis:boolean;allowGif:boolean;enableReportButton:boolean;autoHideThreshold:number;trustedUserThreshold:number};
  referralPolicy:{enabled:boolean;pointsPerRegistration:number;minimumAccountAgeDays:number;dailyClickLimit:number};
  rewardPolicy:{enabled:boolean;publicLeaderboard:boolean;monthlyCalculationDay:number;certificateEnabled:boolean};
  footer:{about:string;newsletterEnabled:boolean;copyright:string};
  version:{currentVersion:string;buildNumber:string;releaseDate:string;environment:"Production"|"Development"|"Staging"};
};

const cmsApi=async<T,>(path:string,options:RequestInit={}):Promise<T>=>{
  const isForm=options.body instanceof FormData;
  const request=()=>fetch(`/api${path}`,{...options,credentials:"include",headers:isForm?options.headers:{"Content-Type":"application/json",...(options.headers||{})}});
  let response=await request();
  if(response.status===401){const refreshed=await fetch("/api/admin/refresh",{method:"POST",credentials:"include",headers:{Origin:location.origin}});if(refreshed.ok)response=await request()}
  if(!response.ok){const body=await response.json().catch(()=>({error:"Request failed"}));throw new Error(body.error||"Request failed")}
  if(response.status===204)return undefined as T;
  return response.json() as Promise<T>;
};
const field=(form:FormData,name:string)=>String(form.get(name)||"").trim();
const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");

export default function CmsPanel({module,isSuperAdmin}:{module:Module;isSuperAdmin:boolean}){
  if(module==="settings")return <SettingsPanel/>;
  if(module==="hero"||module==="news"||module==="pages")return <ContentPanel module={module}/>;
  if(module==="comments")return <CommentsPanel/>;
  if(module==="media")return <MediaPanel/>;
  if(module==="analytics")return <ReadOnlyPanel title="Analytics dashboard" endpoint="/admin/analytics"/>;
  if(module==="audit")return <AuditPanel/>;
  if(module==="search")return <SearchPanel/>;
  if(module==="email")return <EmailPanel/>;
  return <BackupPanel isSuperAdmin={isSuperAdmin}/>;
}

function Notice({error,message}:{error:string;message:string}){return <>{error&&<p className={styles.error} role="alert">{error}</p>}{message&&<p className={styles.success} role="status">{message}</p>}</>}

function SettingsPanel(){
  const [data,setData]=useState<WebsiteSettings|null>(null);const [error,setError]=useState("");const [message,setMessage]=useState("");
  useEffect(()=>{cmsApi<WebsiteSettings>("/admin/settings").then(setData).catch(e=>setError(e.message))},[]);
  const save=async(event:FormEvent<HTMLFormElement>)=>{
    event.preventDefault();if(!data)return;setError("");setMessage("");
    const form=new FormData(event.currentTarget);const bool=(name:string)=>form.get(name)==="on";
    const next:WebsiteSettings={
      general:{websiteName:field(form,"websiteName"),logo:field(form,"logo"),favicon:field(form,"favicon"),footerLogo:field(form,"footerLogo"),websiteDescription:field(form,"websiteDescription"),seoDescription:field(form,"seoDescription"),keywords:field(form,"keywords").split(",").map(x=>x.trim()).filter(Boolean),contactEmail:field(form,"contactEmail"),supportEmail:field(form,"supportEmail"),phone:field(form,"phone"),officeAddress:field(form,"officeAddress"),socialLinks:{facebook:field(form,"facebook_url"),audiomack:field(form,"audiomack_url"),youtube:field(form,"youtube_url"),tiktok:field(form,"tiktok_url")},socialMedia:(["facebook","tiktok","youtube","audiomack"] as const).map(platform=>({platform,enabled:bool(`${platform}_enabled`),url:field(form,`${platform}_url`),order:Number(field(form,`${platform}_order`)||0),customIcon:field(form,`${platform}_icon`)}))},
      appearance:{primaryColor:field(form,"primaryColor"),secondaryColor:field(form,"secondaryColor"),accentColor:field(form,"accentColor"),defaultTheme:field(form,"defaultTheme") as WebsiteSettings["appearance"]["defaultTheme"],typography:field(form,"typography"),heroAnimationSpeed:Number(field(form,"heroAnimationSpeed"))},
      homepage:{enabledSections:Object.fromEntries(["hero","songs","artists","heritage","community","news"].map(key=>[key,bool(`section_${key}`)])),sectionOrder:field(form,"sectionOrder").split(",").map(x=>x.trim()).filter(Boolean),featuredSections:field(form,"featuredSections").split(",").map(x=>x.trim()).filter(Boolean),banner:field(form,"banner")},
      system:Object.fromEntries(["maintenanceMode","registrationEnabled","artistRegistrationEnabled","communityUploadEnabled","musicUploadEnabled","videoUploadEnabled","commentsEnabled","donationEnabled"].map(key=>[key,bool(key)])),
      utilityDock:{position:field(form,"dockPosition") as "right"|"left",visibility:field(form,"dockVisibility") as "entire"|"homepage",liveStatus:field(form,"liveStatus") as "online"|"offline",reportUrl:field(form,"reportUrl"),searchEnabled:bool("searchEnabled"),shareEnabled:bool("shareEnabled")},
      commentPolicy:{approvalRequired:bool("approvalRequired"),requireApprovalForNewUsers:bool("requireApprovalForNewUsers"),minimumApprovedForTrust:Number(field(form,"minimumApprovedForTrust")),spamDetection:bool("spamDetection"),maximumLinks:Number(field(form,"maximumLinks")),maximumCharacters:Number(field(form,"maximumCharacters")),allowReplies:bool("allowReplies"),allowEmojis:bool("allowEmojis"),allowGif:bool("allowGif"),enableReportButton:bool("enableReportButton"),autoHideThreshold:Number(field(form,"autoHideThreshold")),trustedUserThreshold:Number(field(form,"trustedUserThreshold"))},
      referralPolicy:{enabled:bool("referralsEnabled"),pointsPerRegistration:Number(field(form,"pointsPerRegistration")),minimumAccountAgeDays:Number(field(form,"minimumAccountAgeDays")),dailyClickLimit:Number(field(form,"dailyClickLimit"))},
      rewardPolicy:{enabled:bool("rewardsEnabled"),publicLeaderboard:bool("publicLeaderboard"),monthlyCalculationDay:Number(field(form,"monthlyCalculationDay")),certificateEnabled:bool("certificateEnabled")},
      footer:{about:field(form,"footerAbout"),newsletterEnabled:bool("newsletterEnabled"),copyright:field(form,"copyright")},
      version:{currentVersion:field(form,"currentVersion"),buildNumber:field(form,"buildNumber"),releaseDate:field(form,"releaseDate"),environment:field(form,"environment") as "Production"|"Development"|"Staging"}
    };
    try{setData(await cmsApi("/admin/settings",{method:"PUT",body:JSON.stringify(next)}));setMessage("Website settings saved and broadcast to the frontend.")}catch(e){setError(e instanceof Error?e.message:"Unable to save settings")}
  };
  if(!data)return <section className={styles.panel}><div className={styles.skeleton}>Loading website settings…</div></section>;
  return <section className={styles.panel}><div className={styles.panelHead}><div><h2>Website settings</h2><p className={styles.muted}>Manage branding, SEO, appearance, homepage layout and feature availability.</p></div></div><Notice error={error} message={message}/><form className={styles.cmsForm} onSubmit={save}>
    <fieldset><legend>General and SEO</legend><label>Website name<input name="websiteName" defaultValue={data.general.websiteName} required/></label><label>Website logo URL<input name="logo" defaultValue={data.general.logo}/></label><label>Favicon URL<input name="favicon" defaultValue={data.general.favicon}/></label><label>Footer logo URL<input name="footerLogo" defaultValue={data.general.footerLogo}/></label><label className={styles.wide}>Website description<textarea name="websiteDescription" defaultValue={data.general.websiteDescription}/></label><label className={styles.wide}>SEO description<textarea name="seoDescription" defaultValue={data.general.seoDescription}/></label><label className={styles.wide}>Keywords, comma separated<input name="keywords" defaultValue={data.general.keywords.join(", ")}/></label><label>Contact email<input type="email" name="contactEmail" defaultValue={data.general.contactEmail}/></label><label>Support email<input type="email" name="supportEmail" defaultValue={data.general.supportEmail}/></label><label>Phone number<input name="phone" defaultValue={data.general.phone}/></label><label>Office address<input name="officeAddress" defaultValue={data.general.officeAddress}/></label></fieldset>
    <fieldset><legend>Social Media Management</legend>{data.general.socialMedia.sort((a,b)=>a.order-b.order).map(item=><div className={styles.socialSetting} key={item.platform}><strong>{item.platform==="audiomack"?"Audiomack":item.platform[0].toUpperCase()+item.platform.slice(1)}</strong><label className={styles.check}><input type="checkbox" name={`${item.platform}_enabled`} defaultChecked={item.enabled}/> Enabled</label><label>Official profile URL<input type="url" name={`${item.platform}_url`} defaultValue={item.url||data.general.socialLinks[item.platform]||""}/></label><label>Display order<input type="number" min="0" max="20" name={`${item.platform}_order`} defaultValue={item.order}/></label><label>Custom SVG URL (optional)<input type="url" name={`${item.platform}_icon`} defaultValue={item.customIcon}/></label></div>)}</fieldset>
    <fieldset><legend>Floating Utility Dock</legend><label>Position<select name="dockPosition" defaultValue={data.utilityDock.position}><option value="right">Right</option><option value="left">Left</option></select></label><label>Show on<select name="dockVisibility" defaultValue={data.utilityDock.visibility}><option value="entire">Entire website</option><option value="homepage">Homepage only</option></select></label><label>Live status<select name="liveStatus" defaultValue={data.utilityDock.liveStatus}><option value="online">Online</option><option value="offline">Offline</option></select></label><label>Report issue URL<input name="reportUrl" defaultValue={data.utilityDock.reportUrl}/></label><label className={styles.check}><input type="checkbox" name="searchEnabled" defaultChecked={data.utilityDock.searchEnabled}/> Enable global search</label><label className={styles.check}><input type="checkbox" name="shareEnabled" defaultChecked={data.utilityDock.shareEnabled}/> Enable website sharing</label></fieldset>
    <fieldset><legend>Comment policy</legend><label className={styles.check}><input type="checkbox" name="approvalRequired" defaultChecked={data.commentPolicy.approvalRequired}/> Require approval for every comment</label><label className={styles.check}><input type="checkbox" name="requireApprovalForNewUsers" defaultChecked={data.commentPolicy.requireApprovalForNewUsers}/> Review comments from new users</label><label>Approved comments before trust<input type="number" min="1" max="100" name="minimumApprovedForTrust" defaultValue={data.commentPolicy.minimumApprovedForTrust}/></label><label className={styles.check}><input type="checkbox" name="spamDetection" defaultChecked={data.commentPolicy.spamDetection}/> Enable smart spam detection</label><label>Maximum links<input type="number" min="0" max="20" name="maximumLinks" defaultValue={data.commentPolicy.maximumLinks}/></label><label>Maximum characters<input type="number" min="100" max="10000" name="maximumCharacters" defaultValue={data.commentPolicy.maximumCharacters}/></label><label className={styles.check}><input type="checkbox" name="allowReplies" defaultChecked={data.commentPolicy.allowReplies}/> Allow replies</label><label className={styles.check}><input type="checkbox" name="allowEmojis" defaultChecked={data.commentPolicy.allowEmojis}/> Allow emojis</label><label className={styles.check}><input type="checkbox" name="allowGif" defaultChecked={data.commentPolicy.allowGif}/> Allow GIF links</label><label className={styles.check}><input type="checkbox" name="enableReportButton" defaultChecked={data.commentPolicy.enableReportButton}/> Enable report button</label><label>Auto-hide reports threshold<input type="number" min="1" max="100" name="autoHideThreshold" defaultValue={data.commentPolicy.autoHideThreshold}/></label><label>Trusted reporters required<input type="number" min="1" max="100" name="trustedUserThreshold" defaultValue={data.commentPolicy.trustedUserThreshold}/></label></fieldset>
    <fieldset><legend>Appearance</legend>{(["primaryColor","secondaryColor","accentColor"] as const).map(key=><label key={key}>{key.replace("Color"," color")}<input type="color" name={key} defaultValue={data.appearance[key]}/></label>)}<label>Default theme<select name="defaultTheme" defaultValue={data.appearance.defaultTheme}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label>Typography<input name="typography" defaultValue={data.appearance.typography}/></label><label>Hero animation seconds<input name="heroAnimationSpeed" type="number" min="1" max="60" defaultValue={data.appearance.heroAnimationSpeed}/></label></fieldset>
    <fieldset><legend>Homepage layout</legend>{Object.keys(data.homepage.enabledSections).map(key=><label className={styles.check} key={key}><input type="checkbox" name={`section_${key}`} defaultChecked={data.homepage.enabledSections[key]}/> Show {key}</label>)}<label className={styles.wide}>Section order<input name="sectionOrder" defaultValue={data.homepage.sectionOrder.join(", ")}/></label><label className={styles.wide}>Featured sections<input name="featuredSections" defaultValue={data.homepage.featuredSections.join(", ")}/></label><label className={styles.wide}>Homepage banner URL<input name="banner" defaultValue={data.homepage.banner}/></label></fieldset>
    <fieldset><legend>System controls</legend>{Object.entries(data.system).map(([key,value])=><label className={styles.check} key={key}><input type="checkbox" name={key} defaultChecked={value}/>{key.replace(/([A-Z])/g," $1")}</label>)}</fieldset>
    <fieldset><legend>Referrals and rewards</legend><label className={styles.check}><input type="checkbox" name="referralsEnabled" defaultChecked={data.referralPolicy.enabled}/> Enable referrals</label><label>Points per registration<input type="number" min="0" max="10000" name="pointsPerRegistration" defaultValue={data.referralPolicy.pointsPerRegistration}/></label><label>Minimum account age (days)<input type="number" min="0" max="365" name="minimumAccountAgeDays" defaultValue={data.referralPolicy.minimumAccountAgeDays}/></label><label>Daily click limit<input type="number" min="1" max="10000" name="dailyClickLimit" defaultValue={data.referralPolicy.dailyClickLimit}/></label><label className={styles.check}><input type="checkbox" name="rewardsEnabled" defaultChecked={data.rewardPolicy.enabled}/> Enable monthly rewards</label><label className={styles.check}><input type="checkbox" name="publicLeaderboard" defaultChecked={data.rewardPolicy.publicLeaderboard}/> Show public leaderboard</label><label>Monthly calculation day<input type="number" min="1" max="28" name="monthlyCalculationDay" defaultValue={data.rewardPolicy.monthlyCalculationDay}/></label><label className={styles.check}><input type="checkbox" name="certificateEnabled" defaultChecked={data.rewardPolicy.certificateEnabled}/> Enable certificates</label></fieldset>
    <fieldset><legend>Footer and Version</legend><label className={styles.wide}>About Tiv Songs<textarea name="footerAbout" defaultValue={data.footer.about}/></label><label>Copyright<input name="copyright" defaultValue={data.footer.copyright}/></label><label className={styles.check}><input type="checkbox" name="newsletterEnabled" defaultChecked={data.footer.newsletterEnabled}/> Newsletter subscription</label><label>Current version<input name="currentVersion" defaultValue={data.version.currentVersion}/></label><label>Build number<input name="buildNumber" defaultValue={data.version.buildNumber}/></label><label>Release date<input type="date" name="releaseDate" defaultValue={data.version.releaseDate}/></label><label>Environment<select name="environment" defaultValue={data.version.environment}><option>Production</option><option>Development</option><option>Staging</option></select></label></fieldset>
    <button className={`${styles.button} ${styles.primary}`}>Save and publish settings</button>
  </form></section>;
}

function ContentPanel({module}:{module:"hero"|"news"|"pages"}){
  const initialKind=module==="pages"?"about":module;const [kind,setKind]=useState(initialKind);const [items,setItems]=useState<CmsEntry[]>([]);const [editing,setEditing]=useState<CmsEntry|null>(null);const [error,setError]=useState("");const [message,setMessage]=useState("");const [search,setSearch]=useState("");
  const load=useCallback(()=>cmsApi<{items:CmsEntry[]}>(`/admin/cms/${kind}?search=${encodeURIComponent(search)}&pageSize=50`).then(x=>setItems(x.items)).catch(e=>setError(e.message)),[kind,search]);
  useEffect(()=>{load()},[load]);
  const save=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const title=field(form,"title");const body={kind,slug:field(form,"slug")||slugify(title),title,subtitle:field(form,"subtitle")||null,excerpt:field(form,"excerpt")||null,body:field(form,"body")||null,status:field(form,"status"),featured:form.get("featured")==="on",pinned:form.get("pinned")==="on",sortOrder:Number(field(form,"sortOrder")||0),publishAt:field(form,"publishAt")||null,archiveAt:null,imageUrl:field(form,"imageUrl")||null,videoUrl:field(form,"videoUrl")||null,buttonText:field(form,"buttonText")||null,buttonUrl:field(form,"buttonUrl")||null,metadata:kind==="hero"?{overlayOpacity:Number(field(form,"overlayOpacity")||.45),animation:field(form,"animation")}:{category:field(form,"category")},seo:{metaTitle:field(form,"metaTitle"),metaDescription:field(form,"metaDescription"),keywords:field(form,"seoKeywords"),openGraphImage:field(form,"openGraphImage"),canonicalUrl:field(form,"canonicalUrl")}};
    try{await cmsApi(editing?`/admin/cms/${editing.id}`:"/admin/cms",{method:editing?"PUT":"POST",body:JSON.stringify(body)});setEditing(null);event.currentTarget.reset();setMessage(`${title} saved.`);load()}catch(e){setError(e instanceof Error?e.message:"Unable to save content")}};
  const remove=async(item:CmsEntry)=>{if(!confirm(`Delete “${item.title}”? This cannot be undone.`))return;await cmsApi(`/admin/cms/${item.id}`,{method:"DELETE"});load()};
  const pageKinds=["about","privacy","terms","faq","announcement","homepage_section","governor","history","footer_link","contact"];
  return <section className={styles.panel}><div className={styles.panelHead}><div><h2>{module==="hero"?"Hero management":module==="news"?"News and updates":"Pages and website content"}</h2><p className={styles.muted}>Create, edit, schedule, order, preview and publish CMS-managed content.</p></div></div><Notice error={error} message={message}/>
    {module==="pages"&&<label className={styles.toolbarLabel}>Content type<select value={kind} onChange={e=>{setKind(e.target.value);setEditing(null)}}>{pageKinds.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label>}
    <div className={styles.cmsColumns}><form className={styles.form} onSubmit={save} key={editing?.id||kind}><h3>{editing?"Edit":"Create"} {kind.replaceAll("_"," ")}</h3><label>Title<input name="title" defaultValue={editing?.title||""} required/></label><label>Slug<input name="slug" defaultValue={editing?.slug||""} placeholder="Generated from title"/></label><label>Subtitle<input name="subtitle" defaultValue={editing?.subtitle||""}/></label><label>Summary<textarea name="excerpt" defaultValue={editing?.excerpt||""}/></label><label>Rich content<textarea name="body" className={styles.editor} defaultValue={editing?.body||""} placeholder="HTML and formatted text content"/></label><label>Image URL<input name="imageUrl" type="url" defaultValue={editing?.imageUrl||""}/></label><label>YouTube or video URL<input name="videoUrl" type="url" defaultValue={editing?.videoUrl||""}/></label>{kind==="hero"&&<><label>Button text<input name="buttonText" defaultValue={editing?.buttonText||""}/></label><label>Button URL<input name="buttonUrl" defaultValue={editing?.buttonUrl||""}/></label><label>Overlay opacity<input name="overlayOpacity" type="number" min="0" max="1" step=".05" defaultValue=".45"/></label><label>Animation<select name="animation"><option>fade</option><option>slide</option><option>zoom</option></select></label></>} {kind==="news"&&<label>Category<input name="category"/></label>}<label>Publication status<select name="status" defaultValue={editing?.status||"DRAFT"}><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select></label><label>Schedule publication<input name="publishAt" type="datetime-local" defaultValue={editing?.publishAt?.slice(0,16)||""}/></label><label>Display order<input name="sortOrder" type="number" min="0" defaultValue={editing?.sortOrder||0}/></label><label className={styles.check}><input name="featured" type="checkbox" defaultChecked={editing?.featured}/> Featured</label><label className={styles.check}><input name="pinned" type="checkbox" defaultChecked={editing?.pinned}/> Pinned</label><details><summary>SEO controls</summary><label>Meta title<input name="metaTitle"/></label><label>Meta description<textarea name="metaDescription"/></label><label>Keywords<input name="seoKeywords"/></label><label>OpenGraph image<input name="openGraphImage"/></label><label>Canonical URL<input name="canonicalUrl"/></label></details><div className={styles.rowActions}><button className={`${styles.button} ${styles.primary}`}>{editing?"Update":"Create"}</button>{editing&&<button type="button" className={styles.button} onClick={()=>setEditing(null)}>Cancel</button>}</div></form>
    <div><div className={styles.cmsToolbar}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search content"/><a className={styles.button} href={`/api/admin/cms/${kind}/export`} download>Export</a></div><div className={styles.list}>{items.length?items.map(item=><article className={styles.row} key={item.id}><div><h3>{item.title}</h3><p>{item.status} · Order {item.sortOrder} · {new Date(item.updatedAt).toLocaleString()}</p><p>{item.excerpt||item.subtitle||"No summary"}</p></div><div className={styles.rowActions}><button className={styles.button} onClick={()=>setEditing(item)}>Edit</button><button className={styles.button} onClick={()=>window.open(`/api/cms/entries/${item.kind}`,"_blank")}>Preview</button><button className={`${styles.button} ${styles.danger}`} onClick={()=>remove(item)}>Delete</button></div></article>):<div className={styles.empty}>No {kind.replaceAll("_"," ")} records yet.</div>}</div></div></div>
  </section>;
}

function CommentsPanel(){
  const [items,setItems]=useState<CommentItem[]>([]);const [status,setStatus]=useState("PENDING");const [error,setError]=useState("");
  const load=useCallback(()=>cmsApi<{items:CommentItem[]}>(`/admin/comments?status=${status}&pageSize=50`).then(x=>setItems(x.items)).catch(e=>setError(e.message)),[status]);useEffect(()=>{load()},[load]);
  const moderate=async(id:string,next:string,pinned?:boolean)=>{await cmsApi(`/admin/comments/${id}`,{method:"PATCH",body:JSON.stringify(pinned===undefined?{status:next}:{pinned})});load()};
  const action=async(id:string,next:"WARN"|"SUSPEND"|"BAN"|"REPLY")=>{const message=window.prompt(`${next.toLowerCase()} message or reason:`)?.trim();if(!message)return;if(!window.confirm(`Confirm ${next.toLowerCase()} action?`))return;await cmsApi(`/admin/comments/${id}/action`,{method:"POST",body:JSON.stringify({action:next,message})});load()};
  const remove=async(id:string)=>{if(!window.confirm("Permanently delete this comment?"))return;await cmsApi(`/admin/comments/${id}`,{method:"DELETE"});load()};
  return <section className={styles.panel}><div className={styles.panelHead}><div><h2>Comment moderation queue</h2><p className={styles.muted}>Review pending, reported and automatically detected spam. Every action is audited.</p></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>PENDING</option><option>APPROVED</option><option>REJECTED</option><option>SPAM</option><option>HIDDEN</option></select></div><Notice error={error} message=""/><div className={styles.list}>{items.map(item=><article className={styles.row} key={item.id}><div><h3>{item.targetType} · {item.targetId}</h3><p>{item.body}</p><p>{item.likeCount} likes · {item.reportCount} reports · {new Date(item.createdAt).toLocaleString()}</p></div><div className={styles.rowActions}><button className={`${styles.button} ${styles.primary}`} onClick={()=>moderate(item.id,"APPROVED")}>Approve</button><button className={styles.button} onClick={()=>moderate(item.id,"REJECTED")}>Reject</button><button className={styles.button} onClick={()=>moderate(item.id,item.status,!item.pinned)}>{item.pinned?"Unpin":"Pin"}</button><button className={styles.button} onClick={()=>action(item.id,"REPLY")}>Reply</button><button className={styles.button} onClick={()=>action(item.id,"WARN")}>Warn</button><button className={styles.button} onClick={()=>action(item.id,"SUSPEND")}>Suspend</button><button className={styles.button} onClick={()=>action(item.id,"BAN")}>Ban</button><button className={`${styles.button} ${styles.danger}`} onClick={()=>remove(item.id)}>Delete</button></div></article>)}{!items.length&&<div className={styles.empty}>No {status.toLowerCase()} comments.</div>}</div></section>;
}

function MediaPanel(){
  const [items,setItems]=useState<MediaItem[]>([]);const [usage,setUsage]=useState("0");const [error,setError]=useState("");const [message,setMessage]=useState("");
  const load=useCallback(()=>cmsApi<{items:MediaItem[];storageBytes:string}>("/admin/media?pageSize=50").then(x=>{setItems(x.items);setUsage(x.storageBytes)}).catch(e=>setError(e.message)),[]);useEffect(()=>{load()},[load]);
  const upload=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();try{await cmsApi("/admin/media",{method:"POST",body:new FormData(event.currentTarget)});event.currentTarget.reset();setMessage("Media uploaded.");load()}catch(e){setError(e instanceof Error?e.message:"Upload failed")}};
  return <section className={styles.panel}><div className={styles.panelHead}><div><h2>Media library</h2><p className={styles.muted}>Upload and organize website images, audio and video. Storage used: {(Number(usage)/1048576).toFixed(1)} MB.</p></div></div><Notice error={error} message={message}/><form className={styles.inlineForm} onSubmit={upload}><input name="file" type="file" accept="image/*,audio/*,video/*" required/><input name="name" placeholder="Display name"/><input name="folder" placeholder="/homepage"/><input name="altText" placeholder="Accessible description"/><button className={`${styles.button} ${styles.primary}`}>Upload</button></form><div className={styles.mediaGrid}>{items.map(item=><article className={styles.mediaCard} key={item.id}>{item.kind==="image"?<img src={item.url} alt={item.altText||item.name}/>:item.kind==="video"?<video controls preload="metadata" src={item.url}/>:<audio controls preload="none" src={item.url}/>}<strong>{item.name}</strong><small>{item.folder} · {(Number(item.sizeBytes)/1048576).toFixed(1)} MB</small><button className={`${styles.button} ${styles.danger}`} onClick={async()=>{if(confirm(`Delete ${item.name}?`)){await cmsApi(`/admin/media/${item.id}`,{method:"DELETE"});load()}}}>Delete</button></article>)}</div></section>;
}

function ReadOnlyPanel({title,endpoint}:{title:string;endpoint:string}){const [data,setData]=useState<unknown>(null);const [error,setError]=useState("");useEffect(()=>{cmsApi(endpoint).then(setData).catch(e=>setError(e.message))},[endpoint]);return <section className={styles.panel}><div className={styles.panelHead}><div><h2>{title}</h2><p className={styles.muted}>Daily, weekly, monthly and yearly data can be built from these recorded events.</p></div></div><Notice error={error} message=""/><pre className={styles.dataView}>{data?JSON.stringify(data,null,2):"Loading analytics…"}</pre></section>}
function AuditPanel(){const [items,setItems]=useState<AuditItem[]>([]);useEffect(()=>{cmsApi<{items:AuditItem[]}>("/admin/audit?pageSize=100").then(x=>setItems(x.items))},[]);return <section className={styles.panel}><div className={styles.panelHead}><div><h2>Administrator audit log</h2><p className={styles.muted}>Who changed what, when, and from which address.</p></div></div><div className={styles.list}>{items.map(item=><article className={styles.row} key={item.id}><div><h3>{item.action} · {item.entity||"system"}</h3><p>{item.summary}</p><p>{item.actor} ({item.role}) · {item.ipAddress||"unknown IP"} · {new Date(item.createdAt).toLocaleString()}</p></div></article>)}{!items.length&&<div className={styles.empty}>No persisted administrator actions yet.</div>}</div></section>}
function SearchPanel(){const [items,setItems]=useState<SearchRule[]>([]);const load=()=>cmsApi<SearchRule[]>("/admin/search-rules").then(setItems);useEffect(()=>{load()},[]);const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await cmsApi("/admin/search-rules",{method:"POST",body:JSON.stringify({keyword:field(f,"keyword"),type:field(f,"type"),weight:Number(field(f,"weight")),active:true})});e.currentTarget.reset();load()};return <section className={styles.panel}><h2>Search management</h2><form className={styles.inlineForm} onSubmit={save}><input name="keyword" placeholder="Keyword" required/><select name="type"><option>TRENDING</option><option>SUGGESTION</option><option>BLOCKED</option></select><input name="weight" type="number" defaultValue="0"/><button className={`${styles.button} ${styles.primary}`}>Save</button></form><div className={styles.list}>{items.map(item=><article className={styles.row} key={item.id}><div><h3>{item.keyword}</h3><p>{item.type} · weight {item.weight}</p></div><button className={`${styles.button} ${styles.danger}`} onClick={async()=>{await cmsApi(`/admin/search-rules/${item.id}`,{method:"DELETE"});load()}}>Delete</button></article>)}</div></section>}
function EmailPanel(){const [items,setItems]=useState<EmailTemplate[]>([]);const [selected,setSelected]=useState<EmailTemplate|null>(null);const load=()=>cmsApi<EmailTemplate[]>("/admin/email-templates").then(setItems);useEffect(()=>{load()},[]);const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const key=field(f,"key");await cmsApi(`/admin/email-templates/${key}`,{method:"PUT",body:JSON.stringify({name:field(f,"name"),subject:field(f,"subject"),html:field(f,"html"),text:field(f,"text"),active:true})});setSelected(null);load()};return <section className={styles.panel}><h2>Email templates</h2><div className={styles.cmsColumns}><form className={styles.form} onSubmit={save} key={selected?.id||"new"}><label>Template key<input name="key" defaultValue={selected?.key||""} pattern="[a-z0-9_]+" required readOnly={Boolean(selected)}/></label><label>Name<input name="name" defaultValue={selected?.name||""} required/></label><label>Subject<input name="subject" defaultValue={selected?.subject||""} required/></label><label>HTML template<textarea className={styles.editor} name="html" defaultValue={selected?.html||""} required/></label><label>Plain text<textarea name="text" defaultValue={selected?.text||""}/></label><button className={`${styles.button} ${styles.primary}`}>Save template</button></form><div className={styles.list}>{items.map(item=><button className={styles.row} key={item.id} onClick={()=>setSelected(item)}><span><strong>{item.name}</strong><br/><small>{item.key} · {item.subject}</small></span></button>)}</div></div></section>}
function BackupPanel({isSuperAdmin}:{isSuperAdmin:boolean}){return <section className={styles.panel}><div className={styles.panelHead}><div><h2>Backup and exports</h2><p className={styles.muted}>Download a portable CMS configuration backup. Database restore remains an infrastructure operation to protect integrity.</p></div></div>{isSuperAdmin?<a className={`${styles.button} ${styles.primary}`} href="/api/admin/backup" download>Download CMS backup</a>:<p className={styles.error}>Only the super administrator can download a complete backup.</p>}<p className={styles.muted}>Individual content exports are available within Hero, News, and Pages.</p></section>}
