"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import styles from "./admin.module.css";

type Campaign={id:string;name:string;amount:number|null;currency:string;rewardType:string;numberOfWinners:number;rewardDate:string;periodStart:string;periodEnd:string;status:string;winners:Array<{id:string;rank:number;score:number;user:{displayName:string;username:string}}>};
const request=async<T,>(path:string,options:RequestInit={}):Promise<T>=>{const response=await fetch(`/api${path}`,{...options,credentials:"include",headers:{"Content-Type":"application/json",...options.headers}});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error||`Request failed (${response.status})`);return body};

export default function RewardsPanel(){
  const [items,setItems]=useState<Campaign[]>([]),[message,setMessage]=useState(""),[error,setError]=useState("");
  const load=useCallback(()=>request<Campaign[]>("/admin/rewards").then(setItems).catch(reason=>setError(reason.message)),[]);
  useEffect(()=>{void load()},[load]);
  const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setError("");const form=new FormData(event.currentTarget);try{await request("/admin/rewards",{method:"POST",body:JSON.stringify({name:form.get("name"),amount:Number(form.get("amount")||0),currency:form.get("currency"),rewardType:form.get("rewardType"),numberOfWinners:Number(form.get("numberOfWinners")),rewardDate:form.get("rewardDate"),periodStart:form.get("periodStart"),periodEnd:form.get("periodEnd")})});event.currentTarget.reset();setMessage("Reward campaign created.");await load()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to create reward")}};
  const action=async(id:string,kind:"calculate"|"publish")=>{setError("");try{await request(`/admin/rewards/${id}/${kind}`,{method:"POST",body:"{}"});setMessage(kind==="calculate"?"Rankings calculated from verified activity.":"Winners published and notified.");await load()}catch(reason){setError(reason instanceof Error?reason.message:"Reward action failed")}};
  return <section><div className={styles.panelHead}><div><h2>Monthly rewards</h2><p className={styles.muted}>Configure a period, calculate verified rankings, review the result, then publish winners.</p></div></div>{error&&<p className={styles.error}>{error}</p>}{message&&<p className={styles.success}>{message}</p>}<div className={styles.columns}><form className={styles.form} onSubmit={create}><label>Reward name<input name="name" required/></label><label>Reward type<select name="rewardType"><option>CASH</option><option>TOKEN</option><option>GIFT</option><option>CERTIFICATE</option><option>BADGE</option></select></label><label>Amount<input name="amount" type="number" min="0"/></label><label>Currency<input name="currency" defaultValue="NGN" minLength={3} maxLength={3}/></label><label>Number of winners<input name="numberOfWinners" type="number" min="1" max="50" defaultValue="1" required/></label><label>Period begins<input name="periodStart" type="date" required/></label><label>Period ends<input name="periodEnd" type="date" required/></label><label>Reward date<input name="rewardDate" type="date" required/></label><button className={`${styles.button} ${styles.primary}`}>Create reward</button></form><div className={styles.list}>{items.map(item=><article className={styles.row} key={item.id}><div><h3>{item.name}</h3><p>{item.status} · {item.rewardType} · {item.numberOfWinners} winner(s)</p><p>{item.winners.length?item.winners.map(winner=>`${winner.rank}. ${winner.user.displayName} (${winner.score})`).join(" · "):"Rankings not calculated"}</p></div><div className={styles.rowActions}><button className={styles.button} onClick={()=>action(item.id,"calculate")}>Calculate</button>{item.status!=="PUBLISHED"&&<button className={`${styles.button} ${styles.primary}`} disabled={!item.winners.length} onClick={()=>action(item.id,"publish")}>Publish winners</button>}</div></article>)}{!items.length&&<div className={styles.empty}>No reward campaigns yet.</div>}</div></div></section>;
}
