"use client";

import Image from "next/image";
import {useCallback,useEffect,useState} from "react";
import styles from "./UserManagement.module.css";

type UserItem={id:string;email:string;username:string;displayName:string;avatarUrl:string|null;phoneNumber:string|null;country:string|null;state:string|null;accountType:string;status:string;emailVerifiedAt:string|null;createdAt:string;lastLoginAt:string|null;lastActivityAt:string|null;suspendedUntil:string|null;forcePasswordReset:boolean;roles:string[];artist:{stageName:string;imageUrl:string|null;verifiedAt:string|null}|null;_count:{uploads:number;comments:number;communityPosts:number}};
type Activity={sessions:Array<{id:string;ipAddress:string|null;userAgent:string|null;createdAt:string;revokedAt:string|null}>;logins:Array<{id:string;successful:boolean;ipAddress:string|null;browser:string|null;device:string|null;failure:string|null;createdAt:string}>;warnings:Array<{id:string;level:string;reason:string;active:boolean;issuedBy:string;createdAt:string}>;notes:Array<{id:string;body:string;createdBy:string;createdAt:string}>;reports:Array<{id:string;reason:string;status:string;createdAt:string}>;uploads:unknown[];history:unknown[];notifications:unknown[]};
type Directory={items:UserItem[];total:number;page:number;pageSize:number;pages:number};
type DetailTab="overview"|"security"|"warnings"|"notes"|"reports";

async function request<T>(path:string,options:RequestInit={}):Promise<T>{
  const response=await fetch(`/api${path}`,{...options,credentials:"include",headers:{"Content-Type":"application/json",...options.headers}});
  if(!response.ok){const body=await response.json().catch(()=>null) as {error?:string}|null;throw new Error(body?.error||`Request failed (${response.status})`)}
  return response.status===204?undefined as T:response.json();
}

export default function UserManagement({isSuperAdmin}:{isSuperAdmin:boolean}){
  const [data,setData]=useState<Directory>({items:[],total:0,page:1,pageSize:20,pages:1});
  const [search,setSearch]=useState("");const [status,setStatus]=useState("");const [accountType,setAccountType]=useState("");
  const [sort,setSort]=useState("createdAt");const [direction,setDirection]=useState("desc");
  const [page,setPage]=useState(1);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [message,setMessage]=useState("");
  const [selected,setSelected]=useState<UserItem|null>(null);const [activity,setActivity]=useState<Activity|null>(null);const [detailTab,setDetailTab]=useState<DetailTab>("overview");
  const [note,setNote]=useState("");const [warning,setWarning]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const params=new URLSearchParams({page:String(page),pageSize:"20",search,sort,direction});if(status)params.set("status",status);if(accountType)params.set("accountType",accountType);setData(await request<Directory>(`/admin/users?${params}`))}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load users")}finally{setLoading(false)}},[page,search,status,accountType,sort,direction]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer)},[load]);
  const open=async(user:UserItem)=>{setSelected(user);setDetailTab("overview");setActivity(null);try{setActivity(await request<Activity>(`/admin/users/${user.id}/activity`))}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load user activity")}};
  const approveArtist=async()=>{if(!selected?.artist)return;if(!window.confirm(`Approve ${selected.artist.stageName} as a verified artist?`))return;try{await request(`/admin/accounts/${selected.id}/approve`,{method:"PATCH"});setMessage("Artist account approved, activated and notified.");setSelected(null);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to approve artist")}};
  const act=async(action:string)=>{
    if(!selected)return;
    let reason="";if(["SUSPEND","BAN","SOFT_DELETE"].includes(action)){reason=window.prompt(`Reason for ${action.toLowerCase().replaceAll("_"," ")}:`)?.trim()||"";if(!reason)return}
    if(!window.confirm(`Confirm ${action.toLowerCase().replaceAll("_"," ")} for ${selected.email}?`))return;
    try{await request(`/admin/users/${selected.id}/actions`,{method:"POST",body:JSON.stringify({action,reason})});setMessage("Account action completed and recorded in the audit log.");setSelected(null);await load()}catch(reasonValue){setError(reasonValue instanceof Error?reasonValue.message:"Action failed")}
  };
  const addWarning=async()=>{if(!selected||!warning.trim())return;await request(`/admin/users/${selected.id}/warnings`,{method:"POST",body:JSON.stringify({level:"WARNING",reason:warning})});setWarning("");setActivity(await request<Activity>(`/admin/users/${selected.id}/activity`))};
  const addNote=async()=>{if(!selected||!note.trim())return;await request(`/admin/users/${selected.id}/notes`,{method:"POST",body:JSON.stringify({body:note})});setNote("");setActivity(await request<Activity>(`/admin/users/${selected.id}/activity`))};
  const editUser=async()=>{if(!selected)return;const displayName=window.prompt("Full name",selected.displayName);if(!displayName)return;const phoneNumber=window.prompt("Phone number",selected.phoneNumber||"");const country=window.prompt("Country",selected.country||"");const state=window.prompt("State",selected.state||"");await request(`/admin/users/${selected.id}`,{method:"PATCH",body:JSON.stringify({displayName,phoneNumber,country,state})});setSelected(null);setMessage("User details updated.");await load()};
  const editRoles=async()=>{if(!selected)return;const value=window.prompt("Comma-separated roles",selected.roles.join(", "));if(value===null)return;const roles=value.split(",").map(item=>item.trim().toLowerCase()).filter(Boolean);await request(`/admin/users/${selected.id}/roles`,{method:"PATCH",body:JSON.stringify({roles})});setSelected(null);setMessage("User roles updated and audited.");await load()};
  const resetPassword=async()=>{if(!selected)return;const password=window.prompt("Enter a temporary password (minimum 12 characters)");if(!password)return;if(!window.confirm("Reset this password and revoke every active session?"))return;await request(`/admin/users/${selected.id}/password`,{method:"PATCH",body:JSON.stringify({password})});setMessage("Temporary password set. The user must reset it at next sign-in.");setSelected(null)};
  const eraseUser=async()=>{if(!selected||!isSuperAdmin)return;const confirmEmail=window.prompt(`Permanent deletion cannot be undone. Type ${selected.email} to continue:`);if(confirmEmail!==selected.email)return;await request(`/admin/users/${selected.id}/permanent`,{method:"DELETE",body:JSON.stringify({confirmEmail})});setMessage("The soft-deleted user was permanently erased and the action was audited.");setSelected(null);await load()};
  const avatar=(user:UserItem)=>user.avatarUrl||user.artist?.imageUrl;
  return <section className={styles.shell} aria-label="User management">
    <div><h2>User management</h2><p>Search, review and moderate every account. Sensitive actions are confirmed, logged and revoke active sessions where required.</p></div>
    {message&&<p className={styles.notice}>{message}</p>}{error&&<p className={`${styles.notice} ${styles.error}`}>{error}</p>}
    <div className={styles.toolbar}>
      <div className={styles.field}><label htmlFor="user-search">Search users</label><input id="user-search" className={styles.input} value={search} onChange={event=>{setSearch(event.target.value);setPage(1)}} placeholder="Name, username, email or phone"/></div>
      <div className={styles.field}><label htmlFor="user-status">Status</label><select id="user-status" className={styles.select} value={status} onChange={event=>{setStatus(event.target.value);setPage(1)}}><option value="">All statuses</option>{["PENDING","ACTIVE","SUSPENDED","BANNED","INACTIVE","DELETED"].map(value=><option key={value}>{value}</option>)}</select></div>
      <div className={styles.field}><label htmlFor="user-type">Account type</label><select id="user-type" className={styles.select} value={accountType} onChange={event=>{setAccountType(event.target.value);setPage(1)}}><option value="">All types</option><option value="individual">Individual</option><option value="artist">Artist</option></select></div>
      <div className={styles.field}><label htmlFor="user-sort">Sort by</label><select id="user-sort" className={styles.select} value={sort} onChange={event=>setSort(event.target.value)}><option value="createdAt">Registration</option><option value="lastLoginAt">Last login</option><option value="displayName">Name</option><option value="email">Email</option><option value="status">Status</option></select></div>
      <button className={styles.button} onClick={()=>setDirection(value=>value==="asc"?"desc":"asc")} aria-label={`Sort ${direction==="asc"?"descending":"ascending"}`}>{direction==="asc"?"Ascending":"Descending"}</button>
      <a className={styles.button} href={`/api/admin/users/export?search=${encodeURIComponent(search)}&status=${encodeURIComponent(status)}&accountType=${encodeURIComponent(accountType)}`}>Export CSV</a>
    </div>
    <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>User</th><th>Contact</th><th>Location</th><th>Type / roles</th><th>Registered</th><th>Last login</th><th>Status</th><th>Verified</th><th>Content</th><th>Action</th></tr></thead>
      <tbody>{data.items.map(user=><tr key={user.id}><td><div className={styles.profile}>{avatar(user)?<Image className={styles.avatar} src={avatar(user)!} alt="" width={38} height={38}/>:<span className={`${styles.avatar} ${styles.avatarFallback}`}>{user.displayName.slice(0,1).toUpperCase()}</span>}<div><strong>{user.artist?.stageName||user.displayName}</strong><small>@{user.username}</small></div></div></td><td>{user.email}<br/><small>{user.phoneNumber||"No phone"}</small></td><td>{[user.state,user.country].filter(Boolean).join(", ")||"—"}</td><td>{user.accountType}<br/><small>{user.roles.join(", ")||"No role"}</small></td><td>{new Date(user.createdAt).toLocaleDateString()}</td><td>{user.lastLoginAt?new Date(user.lastLoginAt).toLocaleString():"Never"}</td><td><span className={`${styles.status} ${styles[user.status as keyof typeof styles]||""}`}>{user.status}</span></td><td>{user.emailVerifiedAt?"Email ":""}{user.artist?.verifiedAt?"Artist":""}{!user.emailVerifiedAt&&!user.artist?.verifiedAt?"No":" "}</td><td>{user._count.uploads} uploads<br/><small>{user._count.comments} comments</small></td><td><button className={`${styles.button} ${styles.primary}`} onClick={()=>void open(user)}>View</button></td></tr>)}</tbody>
    </table>{!loading&&!data.items.length&&<div className={styles.empty}>No users match these filters.</div>}{loading&&<div className={styles.empty}>Loading users…</div>}</div>
    <div className={styles.pager}><span>{data.total} users · Page {data.page} of {data.pages}</span><div><button className={styles.button} disabled={page<=1} onClick={()=>setPage(value=>value-1)}>Previous</button><button className={styles.button} disabled={page>=data.pages} onClick={()=>setPage(value=>value+1)}>Next</button></div></div>
    {selected&&<div className={styles.backdrop} role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null)}}><aside className={styles.drawer} role="dialog" aria-modal="true" aria-labelledby="user-detail-title">
      <div className={styles.drawerHead}><div><small>{selected.accountType.toUpperCase()} ACCOUNT</small><h2 id="user-detail-title">{selected.displayName}</h2><p>@{selected.username} · {selected.email}</p></div><button className={styles.button} onClick={()=>setSelected(null)} aria-label="Close user details">Close</button></div>
      <nav className={styles.tabs} aria-label="User details">{(["overview","security","warnings","notes","reports"] as DetailTab[]).map(value=><button className={`${styles.button} ${detailTab===value?styles.activeTab:""}`} key={value} onClick={()=>setDetailTab(value)}>{value[0].toUpperCase()+value.slice(1)}</button>)}</nav>
      {selected.accountType==="artist"&&selected.status==="PENDING"&&selected.artist&&<div className={styles.card}><h3>Artist application awaiting approval</h3><p>Review the stage name and profile details, then approve to activate this account and unlock artist uploads.</p><div className={styles.actions}><button className={`${styles.button} ${styles.primary}`} onClick={()=>void approveArtist()}>Approve artist account</button><button className={`${styles.button} ${styles.danger}`} onClick={()=>void act("SUSPEND")}>Reject / suspend</button></div></div>}
      {detailTab==="overview"&&<><div className={`${styles.card} ${styles.grid}`}><p><span>Status</span>{selected.status}</p><p><span>Roles</span>{selected.roles.join(", ")||"None"}</p><p><span>Phone</span>{selected.phoneNumber||"Not provided"}</p><p><span>Location</span>{[selected.state,selected.country].filter(Boolean).join(", ")||"Not provided"}</p><p><span>Last activity</span>{selected.lastActivityAt?new Date(selected.lastActivityAt).toLocaleString():"Never"}</p><p><span>Content</span>{selected._count.uploads} uploads, {selected._count.comments} comments</p></div><div className={styles.card}><h3>Account actions</h3><div className={styles.actions}><button className={styles.button} onClick={()=>void editUser()}>Edit details</button><button className={styles.button} onClick={()=>void editRoles()}>Assign roles</button><button className={styles.button} onClick={()=>void resetPassword()}>Reset password</button><button className={styles.button} onClick={()=>void act("VERIFY_EMAIL")}>Verify email</button>{selected.artist&&<button className={styles.button} onClick={()=>void act("VERIFY_ARTIST")}>Verify artist</button>}<button className={styles.button} onClick={()=>void act("FORCE_LOGOUT")}>Force logout</button><button className={styles.button} onClick={()=>void act("FORCE_PASSWORD_RESET")}>Require password reset</button>{selected.status==="SUSPENDED"?<button className={styles.button} onClick={()=>void act("UNSUSPEND")}>Unsuspend</button>:<button className={styles.button} onClick={()=>void act("SUSPEND")}>Suspend</button>}{selected.status==="BANNED"?<button className={styles.button} onClick={()=>void act("UNBAN")}>Unban</button>:<button className={`${styles.button} ${styles.danger}`} onClick={()=>void act("BAN")}>Ban</button>}{selected.status==="DELETED"?<button className={styles.button} onClick={()=>void act("RESTORE")}>Restore</button>:<button className={`${styles.button} ${styles.danger}`} onClick={()=>void act("SOFT_DELETE")}>Soft delete</button>}{isSuperAdmin&&selected.status==="DELETED"&&<button className={`${styles.button} ${styles.danger}`} onClick={()=>void eraseUser()}>Permanently erase</button>}</div></div></>}
      {detailTab==="security"&&<div className={`${styles.card} ${styles.list}`}><h3>Recent login attempts</h3>{activity?.logins.length?activity.logins.map(item=><article key={item.id}><strong>{item.successful?"Successful":"Failed"}</strong> · {item.browser||"Unknown browser"} / {item.device||"Unknown device"}<br/><small>{item.ipAddress||"Unknown IP"} · {new Date(item.createdAt).toLocaleString()} {item.failure&&`· ${item.failure}`}</small></article>):<p>No login attempts recorded.</p>}</div>}
      {detailTab==="warnings"&&<div className={styles.card}><h3>Warnings</h3><textarea className={styles.textarea} value={warning} onChange={event=>setWarning(event.target.value)} placeholder="Explain the policy issue to the user"/><button className={`${styles.button} ${styles.primary}`} onClick={()=>void addWarning()}>Issue warning</button><div className={styles.list}>{activity?.warnings.map(item=><article key={item.id}><strong>{item.level} · {item.active?"Active":"Resolved"}</strong><p>{item.reason}</p><small>{item.issuedBy} · {new Date(item.createdAt).toLocaleString()}</small></article>)}</div></div>}
      {detailTab==="notes"&&<div className={styles.card}><h3>Private administrator notes</h3><textarea className={styles.textarea} value={note} onChange={event=>setNote(event.target.value)} placeholder="Only administrators can see this note"/><button className={`${styles.button} ${styles.primary}`} onClick={()=>void addNote()}>Add note</button><div className={styles.list}>{activity?.notes.map(item=><article key={item.id}><p>{item.body}</p><small>{item.createdBy} · {new Date(item.createdAt).toLocaleString()}</small></article>)}</div></div>}
      {detailTab==="reports"&&<div className={`${styles.card} ${styles.list}`}><h3>Reports involving this user</h3>{activity?.reports.length?activity.reports.map(item=><article key={item.id}><strong>{item.status}</strong><p>{item.reason}</p><small>{new Date(item.createdAt).toLocaleString()}</small></article>):<p>No reports involving this user.</p>}</div>}
    </aside></div>}
  </section>
}
