import express from "express";
import helmet from "helmet";
import cors from "cors";
import compression from "compression";
import cookieParser from "cookie-parser";
import { rateLimit } from "express-rate-limit";
import { env } from "./config/env.js";
import { api } from "./routes/index.js";
import { errorHandler } from "./middleware/error.js";
import {apiLogger} from "./platform/logger.js";

export const app=express();
const webOrigin=new URL(env.WEB_URL).origin;
app.set("trust proxy",1);
app.disable("x-powered-by");
app.use(helmet({crossOriginResourcePolicy:{policy:"cross-origin"}}));
app.use(cors({origin:webOrigin,credentials:true}));
app.use(compression());
app.use((req,res,next)=>{const started=performance.now();res.on("finish",()=>apiLogger.info({method:req.method,path:req.path,status:res.statusCode,durationMs:Math.round((performance.now()-started)*100)/100,ip:req.ip},"request completed"));next()});
app.use(rateLimit({windowMs:60_000,limit:180,standardHeaders:"draft-8"}));
const loginLimiter=rateLimit({windowMs:15*60_000,limit:10,standardHeaders:"draft-8",legacyHeaders:false,message:{error:"Too many authentication attempts. Try again later."}});
app.use(["/api/account/login","/api/admin/login"],loginLimiter);
app.use("/api/account/register",rateLimit({windowMs:60*60_000,limit:5,standardHeaders:"draft-8",legacyHeaders:false,message:{error:"Too many registration attempts. Try again later."}}));
app.use("/api/comments",rateLimit({windowMs:60_000,limit:12,standardHeaders:"draft-8",legacyHeaders:false,message:{error:"You are commenting too quickly. Please wait a moment."}}));
app.use(express.json({limit:"1mb"}));
app.use(express.urlencoded({extended:false,limit:"1mb"}));
app.use(cookieParser());
app.use((req,res,next)=>{
  if(["GET","HEAD","OPTIONS"].includes(req.method))return next();
  const origin=req.get("origin");
  const fetchSite=req.get("sec-fetch-site");
  if((origin&&origin!==webOrigin)||fetchSite==="cross-site")return void res.status(403).json({error:"Cross-site request rejected"});
  next();
});
app.use("/api",api);
app.use((_req,res)=>res.status(404).json({error:"Route not found"}));
app.use(errorHandler);
