import express from "express";
import helmet from "helmet";
import cors from "cors";
import compression from "compression";
import cookieParser from "cookie-parser";
import { rateLimit } from "express-rate-limit";
import { env } from "./config/env.js";
import { api } from "./routes/index.js";
import { errorHandler } from "./middleware/error.js";

export const app=express();
app.set("trust proxy",1);
app.use(helmet({crossOriginResourcePolicy:{policy:"cross-origin"}}));
app.use(cors({origin:env.WEB_URL,credentials:true}));
app.use(compression());
app.use(rateLimit({windowMs:60_000,limit:180,standardHeaders:"draft-8"}));
app.use(express.json({limit:"1mb"}));
app.use(express.urlencoded({extended:false,limit:"1mb"}));
app.use(cookieParser());
app.use("/api",api);
app.use((_req,res)=>res.status(404).json({error:"Route not found"}));
app.use(errorHandler);
