"use client";

import Link from "next/link";
import {FormEvent,useCallback,useEffect,useState} from "react";
import styles from "./CommentSection.module.css";

type Comment={id:string;body:string;pinned:boolean;likeCount:number;reportCount:number;createdAt:string;author:{displayName:string;avatarUrl:string|null};replies:Array<Comment>};
type TargetType="song"|"video"|"community"|"history"|"artist";
type CommentPage={items:Comment[];pagination:{page:number;pages:number;total:number}};
const request=async<T,>(path:string,options:RequestInit={}):Promise<T>=>{const run=()=>fetch(`/api${path}`,{...options,credentials:"include",headers:{"Content-Type":"application/json",...(options.headers||{})}});let response=await run();if(response.status===401){const refreshed=await fetch("/api/account/refresh",{method:"POST",credentials:"include",headers:{Origin:location.origin}});if(refreshed.ok)response=await run()}if(!response.ok){const body=await response.json().catch(()=>({error:"Request failed"}));throw new Error(body.error||"Request failed")}return response.json() as Promise<T>};

export default function CommentSection({targetType,targetId,title="Join the conversation"}:{targetType:TargetType;targetId:string;title?:string}){
  const [items,setItems]=useState<Comment[]>([]),[sort,setSort]=useState("newest"),[message,setMessage]=useState(""),[error,setError]=useState(""),[replyTo,setReplyTo]=useState<string|null>(null),[page,setPage]=useState(1),[pages,setPages]=useState(1),[submitting,setSubmitting]=useState(false);
  const load=useCallback((nextPage=1,append=false)=>fetch(`/api/comments/${targetType}/${encodeURIComponent(targetId)}?sort=${sort}&page=${nextPage}&pageSize=20&format=page`,{credentials:"include"}).then(async response=>{if(!response.ok)throw new Error("Comments are unavailable");return response.json() as Promise<CommentPage>}).then(data=>{setItems(current=>append?[...current,...data.items]:data.items);setPage(data.pagination.page);setPages(data.pagination.pages)}).catch(reason=>setError(reason.message)),[sort,targetId,targetType]);
  useEffect(()=>{void load();const events=new EventSource("/api/cms/events");const refresh=()=>void load();for(const event of ["comment.approved","comment.updated","comment.liked","comment.hidden"])events.addEventListener(event,refresh);return()=>events.close()},[load]);
  const submit=async(event:FormEvent<HTMLFormElement>,parentId?:string)=>{event.preventDefault();setError("");setMessage("");setSubmitting(true);const element=event.currentTarget,form=new FormData(element);try{const result=await request<{message?:string;status:string}>("/comments",{method:"POST",body:JSON.stringify({targetType,targetId,parentId,body:String(form.get("body")||"")})});element.reset();setReplyTo(null);setMessage(result.message||"Your comment was received.");if(result.status==="APPROVED")void load()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to submit comment")}finally{setSubmitting(false)}};
  const react=async(id:string,action:"like"|"report")=>{try{await request(`/comments/${id}/${action}`,{method:"POST",body:action==="report"?JSON.stringify({reason:"OTHER"}):"{}"});action==="like"?void load():setMessage("Comment reported for administrator review.")}catch(reason){setError(reason instanceof Error?reason.message:"Please sign in to continue")}};
  return <section className={styles.section} aria-labelledby={`comments-${targetId}`}><div className={styles.inner}><header className={styles.head}><div><span>COMMUNITY VOICES</span><h2 id={`comments-${targetId}`}>{title}</h2><p>Trusted contributors publish immediately; suspicious activity is reviewed.</p></div><label>Sort<select value={sort} onChange={event=>{setSort(event.target.value);setPage(1)}}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="liked">Most liked</option><option value="replied">Most replied</option></select></label></header>
    {message&&<p className={styles.success} role="status">{message}</p>}{error&&<p className={styles.error} role="alert">{error} {error.toLowerCase().includes("sign")&&<Link href="/account">Sign in</Link>}</p>}
    <form className={styles.form} onSubmit={event=>submit(event)} aria-busy={submitting}><label htmlFor={`comment-${targetId}`}>Share a respectful comment</label><textarea id={`comment-${targetId}`} name="body" minLength={2} maxLength={3000} required placeholder="Add to the conversation…" disabled={submitting}/><div><small>{submitting?"Checking your comment…":"Keep discussion constructive and relevant."}</small><button disabled={submitting}>{submitting?"Posting…":"Post comment"}</button></div></form>
    <div className={styles.list}>{items.map(item=><article className={styles.comment} key={item.id}><div className={styles.avatar}>{item.author.avatarUrl?<img src={item.author.avatarUrl} alt=""/>:item.author.displayName.slice(0,1).toUpperCase()}</div><div className={styles.commentBody}><header><strong>{item.author.displayName}</strong>{item.pinned&&<span>Pinned</span>}<time dateTime={item.createdAt}>{new Date(item.createdAt).toLocaleDateString()}</time></header><p>{item.body}</p><div className={styles.actions}><button type="button" onClick={()=>react(item.id,"like")}>Like · {item.likeCount}</button><button type="button" onClick={()=>setReplyTo(replyTo===item.id?null:item.id)}>Reply · {item.replies?.length||0}</button><button type="button" onClick={()=>react(item.id,"report")}>Report</button></div>{replyTo===item.id&&<form className={styles.replyForm} onSubmit={event=>submit(event,item.id)}><textarea name="body" required minLength={2} maxLength={3000} placeholder={`Reply to ${item.author.displayName}`}/><button>Post reply</button></form>}{item.replies?.map(reply=><article className={styles.reply} key={reply.id}><strong>{reply.author.displayName}</strong><p>{reply.body}</p><small>{new Date(reply.createdAt).toLocaleDateString()}</small></article>)}</div></article>)}{!items.length&&<div className={styles.empty}>No approved comments yet. Start the conversation.</div>}{page<pages&&<button className={styles.loadMore} onClick={()=>void load(page+1,true)}>Load more comments</button>}</div>
  </div></section>
}
