"use client";

import Link from "next/link";
import {useCallback,useEffect,useRef,useState} from "react";
import styles from "./HeroSlider.module.css";

type Slide={id:string;title:string;subtitle:string|null;excerpt:string|null;imageUrl:string|null;videoUrl:string|null;buttonText:string|null;buttonUrl:string|null;metadata?:{animation?:string}|null};
const fallback:Slide={id:"default",title:"The home of Tiv music & culture.",subtitle:"Benue State · Nigeria",excerpt:"Stream, discover and preserve authentic Tiv sound and cultural heritage for generations.",imageUrl:"/assets/kings/james-ayatse.jpg",videoUrl:null,buttonText:"Start listening",buttonUrl:"#music",metadata:{animation:"fade"}};

export default function HeroSlider(){
  const [slides,setSlides]=useState<Slide[]>([fallback]),[active,setActive]=useState(0),[enabled,setEnabled]=useState(true),[speed,setSpeed]=useState(7),[paused,setPaused]=useState(false);const touchStart=useRef<number|null>(null);
  const load=useCallback(()=>Promise.all([fetch("/api/cms/entries/hero",{cache:"no-store"}),fetch("/api/cms/settings",{cache:"no-store"})]).then(async([entries,settingsResponse])=>{const items=entries.ok?await entries.json() as Slide[]:[];const settings=settingsResponse.ok?await settingsResponse.json() as {homepage?:{enabledSections?:Record<string,boolean>};appearance?:{heroAnimationSpeed?:number}}:{};setSlides(items.length?items:[fallback]);setEnabled(settings.homepage?.enabledSections?.hero!==false);setSpeed(Math.max(1,settings.appearance?.heroAnimationSpeed||7));setActive(0)}).catch(()=>setSlides([fallback])),[]);
  useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener("cms:content-updated",refresh);return()=>window.removeEventListener("cms:content-updated",refresh)},[load]);
  const move=useCallback((direction:number)=>setActive(value=>(value+direction+slides.length)%slides.length),[slides.length]);
  useEffect(()=>{if(slides.length<2||paused)return;const timer=window.setInterval(()=>move(1),speed*1000);return()=>window.clearInterval(timer)},[slides.length,speed,paused,move]);
  if(!enabled)return null;
  return <section className={styles.hero} aria-roledescription="carousel" aria-label="Featured Tiv Songs content" tabIndex={0} onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocus={()=>setPaused(true)} onBlur={event=>{if(!event.currentTarget.contains(event.relatedTarget))setPaused(false)}} onKeyDown={event=>{if(event.key==="ArrowLeft")move(-1);if(event.key==="ArrowRight")move(1)}} onTouchStart={event=>{touchStart.current=event.touches[0]?.clientX??null;setPaused(true)}} onTouchEnd={event=>{if(touchStart.current!==null){const distance=(event.changedTouches[0]?.clientX??touchStart.current)-touchStart.current;if(Math.abs(distance)>45)move(distance>0?-1:1)}touchStart.current=null;setPaused(false)}}>{slides.map((slide,index)=><article className={`${styles.slide} ${index===active?styles.active:""}`} aria-hidden={index!==active} key={slide.id}><div className={styles.copy}><span className={styles.eyebrow}>{slide.subtitle||"FEATURED MUSIC"}</span><h1>{slide.title}</h1>{slide.excerpt&&<p>{slide.excerpt}</p>}<div className={styles.actions}>{slide.buttonText&&slide.buttonUrl&&<Link className={styles.primary} href={slide.buttonUrl}>{slide.buttonText}</Link>}<Link className={styles.secondary} href="/#songs">Explore music</Link></div><div className={styles.counter}><strong>{String(index+1).padStart(2,"0")}</strong><span>/ {String(slides.length).padStart(2,"0")}</span></div></div><div className={styles.visual}>{slide.videoUrl?<video className={styles.media} src={slide.videoUrl} autoPlay muted loop playsInline/>:slide.imageUrl?<img className={styles.media} src={slide.imageUrl} alt={`${slide.title} featured artwork`}/>:<img className={styles.media} src="/assets/tiv-song-logo.jpeg" alt="Tiv Songs"/>}</div></article>)}{slides.length>1&&<><button className={`${styles.arrow} ${styles.previous}`} aria-label="Previous featured slide" onClick={()=>move(-1)}>←</button><button className={`${styles.arrow} ${styles.next}`} aria-label="Next featured slide" onClick={()=>move(1)}>→</button><div className={styles.controls}>{slides.map((slide,index)=><button key={slide.id} aria-label={`Show slide ${index+1}: ${slide.title}`} aria-current={index===active} onClick={()=>setActive(index)}/>)}</div></>}</section>;
}
