import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {publicApi,siteUrl} from "../../lib/public-api";
import ShareButton from "../../components/ShareButton";
import SiteFooter from "../../components/SiteFooter";
import FollowButton from "./FollowButton";
import styles from "./profile.module.css";

type Profile={id:string;username:string;displayName:string;avatarUrl:string|null;coverUrl:string|null;bio:string|null;country:string|null;state:string|null;preferredGenre:string|null;contributorRank:string;contributorVerifiedAt:string|null;createdAt:string;artist:{stageName:string;bio:string|null;imageUrl:string|null;coverImageUrl:string|null;genre:string|null;verifiedAt:string|null}|null;badges:Array<{awardedAt:string;badge:{key:string;name:string;description:string;icon:string|null}}> ;stats:{songs:number;videos:number;streams:number;downloads:number;likes:number;comments:number;followers:number;following:number;referrals:number;score:number;rank:string};contributedSongs:Array<{id:string;title:string;slug:string;artworkUrl:string|null;playCount:string;downloadCount:string}>;contributedVideos:Array<{id:string;title:string;slug:string;thumbnailUrl:string|null;viewCount:string;downloadCount:string}>};
const load=(username:string)=>publicApi<Profile>(`/contributors/${encodeURIComponent(username)}`);
export async function generateMetadata({params}:{params:Promise<{username:string}>}):Promise<Metadata>{const {username}=await params,profile=await load(username);if(!profile)return {title:"Contributor not found"};const title=`${profile.artist?.stageName||profile.displayName} · Tiv Songs Contributor`;return {title,description:profile.bio||profile.artist?.bio||`View @${profile.username} on Tiv Songs.`,alternates:{canonical:`${siteUrl}/contributor/${profile.username}`},openGraph:{title,description:profile.bio||"Tiv Songs contributor profile",images:profile.avatarUrl?[profile.avatarUrl]:[]}}}
export default async function ContributorPage({params}:{params:Promise<{username:string}>}){const {username}=await params,profile=await load(username);if(!profile)notFound();const title=profile.artist?.stageName||profile.displayName;return <main className={styles.page}><nav><Link href="/">← Tiv Songs</Link><Link href="/leaderboard">Leaderboard</Link></nav><header className={styles.hero} style={profile.coverUrl||profile.artist?.coverImageUrl?{backgroundImage:`linear-gradient(#210038bb,#210038ee),url(${profile.coverUrl||profile.artist?.coverImageUrl})`}:undefined}><div className={styles.avatar}>{profile.avatarUrl||profile.artist?.imageUrl?<img src={profile.avatarUrl||profile.artist?.imageUrl||""} alt=""/>:title.slice(0,1)}</div><div><span>PUBLIC CONTRIBUTOR PROFILE</span><h1>{title}</h1><p>@{profile.username} · Joined {new Date(profile.createdAt).toLocaleDateString()}</p><div className={styles.actions}><FollowButton username={profile.username} initialFollowers={profile.stats.followers}/><ShareButton title={title} text={`Discover ${title} on Tiv Songs`} url={`${siteUrl}/contributor/${profile.username}`} entityType="contributor" entityId={profile.id}/></div></div></header><section className={styles.content}><div className={styles.verify}>{profile.artist?.verifiedAt||profile.contributorVerifiedAt?<strong>✓ Verified contributor</strong>:<strong>Contributor</strong>}<span>{profile.stats.rank}</span><span>{profile.preferredGenre||profile.artist?.genre||"Tiv culture"}</span><span>{[profile.state,profile.country].filter(Boolean).join(", ")}</span></div><p className={styles.bio}>{profile.bio||profile.artist?.bio||"This contributor is preserving Tiv creativity through Tiv Songs."}</p><div className={styles.stats}>{Object.entries(profile.stats).filter(([key])=>key!=="rank"&&key!=="score").map(([key,value])=><div key={key}><strong>{value}</strong><span>{key}</span></div>)}</div>{profile.badges.length>0&&<section><h2>Achievements</h2><div className={styles.badges}>{profile.badges.map(item=><article key={item.badge.key}><b>★</b><strong>{item.badge.name}</strong><small>{item.badge.description}</small></article>)}</div></section>}<section><h2>Published music</h2><div className={styles.cards}>{profile.contributedSongs.map(item=><Link href={`/song/${item.slug}`} key={item.id}><strong>{item.title}</strong><span>{item.playCount} streams · {item.downloadCount} downloads</span></Link>)}{!profile.contributedSongs.length&&<p>No published songs yet.</p>}</div></section><section><h2>Published videos</h2><div className={styles.cards}>{profile.contributedVideos.map(item=><Link href={`/video/${item.slug}`} key={item.id}><strong>{item.title}</strong><span>{item.viewCount} views</span></Link>)}{!profile.contributedVideos.length&&<p>No published videos yet.</p>}</div></section></section><SiteFooter variant="community"/></main>}
